### ISSUE TITLE
Rename repository and package

### ISSUE THREAD

**Issue by benedfit** [emartech/gulp-pug-lint#3]
Because of reasons; https://github.com/pugjs/jade/issues/2184, Jade is being renamed to Pug in the not so distant future. At this point `jade-lint` will be deprecated in favour of `pug-lint`. 

I'll keep you posted as to when this is happening

**Comment by jzsfkzm** [comment]
@benedfit thanks, we'll keep an eye out.

**Comment by benedfit** [comment]
`pug-lint@2.1.1` has now been published, `jade-lint` will be deprecated at some point

**Comment by jzsfkzm** [comment]
Thanks @benedfit, I'll go around our repos with my Renamer3000 soon.

**Comment by jzsfkzm** [comment]
Hey @benedfit, I renamed both the repository and the package is also published under the new name. Thanks for the heads up.
